pipeline:
  name: Jmeter
  identifier: Jmeter
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build and test
        identifier: Build_and_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Ravalika
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      echo maven build
                      mvn -version
                      mvn clean install
    - stage:
        name: jmeter
        identifier: jmeter
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      set -e
                      cd /harness/jmeter
                      rm -f testresults.jtl
                      chmod +x jmeter
                      /harness/jmeter/jmeter -n -t CSVSample.jmx -l testresults.jtl
                      rm -rf /harness/jmeter/report
                      /harness/jmeter/jmeter -g /harness/jmeter/testresults.jtl -e -o /harness/jmeter/report
                      ls -l /harness/jmeter/report
                      ls
                      cat /harness/jmeter/report/index.html
  properties:
    ci:
      codebase:
        connectorRef: Ravalika
        build: <+input>
